apiVersion: v1
kind: Deployment
metadata: 
  name: hello-world-deployment
spec: 
  replicas: 2 # tells deployment to run 2 pods matching the template
  template: # create pods using pod definition in this template
    metadata: 
      labels: 
        app: hello-world
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
